version: "3.6"
services: 
  mysql:
    image: mysql:5.7
    restart: always
    env_file:
      - .env    
    volumes:
      - ./data:/data


  wordpress:
    build: ./wordpress
    image: dri_landing_page
    restart: always
    env_file:
      - .env    
    ports:
      - 8080:80
    volumes:
      - ./wordpress:/var/www/html
    depends_on:
      - mysql