version: "3.6"
services: 
  mysql:
    build: ./data
    env_file:
      - .env

  wordpress:
    build: ./wordpress
    env_file:
      - .env    
    ports:
      - 80:80
    volumes:
      - ./wordpress:/var/www/html
    depends_on:
      - mysql